### ISSUE TITLE
stringify-errors

### ISSUE THREAD

**Issue by osher** [smallilies/smallilies#1]
Hi, 

I would like to ask you about your package stringify-errors, and I don't know how to contact you...

I can't find the original repository, and I would like to submit a PR

how can I do that?

If yo don't intend to maintain this package - please consider releasing the name

thanks
    Osher

**Comment by smallilies** [comment]
Please feel free to take over, I've added you as the owner of [stringify-error on npm](https://www.npmjs.com/package/stringify-error).

**Comment by osher** [comment]
I have to soften my spam filters :(
my bad, I totally missed your reply and acted too fast with a [new name](https://www.npmjs.com/package/error-stringify)...

but thanks, I'll try to make of it something good!
